# Generated by Django 5.1.4 on 2026-02-26 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('learning', 'Learning'), ('assessed', 'Assessed'), ('project_done', 'Project Done'), ('verified', 'Verified')], default='not_started', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_progress',
            },
        ),
        migrations.CreateModel(
            name='RoadmapEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completion_pct', models.FloatField(default=0.0)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='roadmaps.roadmap')),
            ],
            options={
                'db_table': 'roadmap_enrollments',
            },
        ),
    ]
