# Generated by Django 5.1.4 on 2026-02-26 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('target_role', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_weeks', models.PositiveIntegerField(default=8)),
                ('skill_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('mdn_url', models.URLField(blank=True)),
                ('estimated_days', models.PositiveIntegerField(default=7)),
                ('is_gateway', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='roadmaps.roadmap')),
            ],
            options={
                'db_table': 'skill_nodes',
                'ordering': ['order'],
            },
        ),
    ]
